source "https://rubygems.org"
ruby ">= 3.2"
gem "rails", "8.1.3.1"
# Rails 8.1's JSON decoder passes an options hash unsupported by JSON 3.
gem "json", "~> 2.19"
gem "sqlite3", "~> 2.0"
gem "puma", "~> 7.0"
gem "tzinfo-data", platforms: %i[windows jruby]
group :test do
  gem "minitest", "~> 5.0"
end
