import { test, expect } from '@playwright/test'

async function fillNames(page) {
  await page.locator('#last_name').fill('テスト患者')
  await page.locator('#first_name').fill('一郎')
  await page.locator('#last_name_kana').fill('テストカンジャ')
  await page.locator('#first_name_kana').fill('イチロウ')
}
test('AC-01/02/04 create without birthday, edit and reload', async ({ page }) => {
  await page.goto('/patients/new')
  await fillNames(page)
  await page.getByRole('button', { name: '登録', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('status')).toContainText('登録しました')
  await page.getByRole('button', { name: '編集', exact: true }).click()
  await expect(page.locator('#first_name')).toHaveValue('一郎')
  const editUrl = page.url()
  await page.locator('#first_name').fill('次郎')
  await page.locator('#birth_date').fill('2000-02-29')
  await page.getByRole('button', { name: '登録', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goto(editUrl)
  await expect(page.locator('#first_name')).toHaveValue('次郎')
  await expect(page.locator('#birth_date')).toHaveValue('2000-02-29')
  await page.locator('#birth_date').fill('')
  await page.getByRole('button', { name: '登録', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goto(editUrl)
  await expect(page.locator('#birth_date')).toHaveValue('')
})
test('AC-03 validation, footer order, focus trap and discard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新規', exact: true }).click()
  await expect(page.locator('#last_name')).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.locator('#close')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('#last_name')).toBeFocused()
  await page.getByRole('button', { name: '登録', exact: true }).click()
  await expect(page.locator('#last_name')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('#birth_date')).toHaveAttribute('aria-invalid', 'false')
  await expect(page.locator('footer button')).toHaveText(['登録', '閉じる'])
  await page.locator('#last_name').fill('未保存')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '戻る', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '戻る', exact: true }).click()
  await expect(page.locator('#last_name')).toHaveValue('未保存')
  await page.locator('#close').click()
  await page.getByRole('button', { name: '中止' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('#new')).toBeFocused()
})
test('AC-04 404 and network failure retain usable close', async ({ page }) => {
  await page.goto('/patients/999999999/edit')
  await expect(page.getByRole('alert')).toContainText('見つかりません')
  await expect(page.getByRole('button', { name: '登録', exact: true })).toBeDisabled()
  await page.locator('#close').click()
  await page.getByRole('button', { name: '新規', exact: true }).click()
  await fillNames(page)
  await page.route('**/api/patients', route => route.abort())
  await page.getByRole('button', { name: '登録', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('保存結果を確認できません')
  await expect(page.locator('#first_name')).toHaveValue('一郎')
  await expect(page.getByRole('button', { name: '登録', exact: true })).toBeDisabled()
})
test('AC-06 compact desktop and narrow layout', async ({ page }) => {
  await page.goto('/patients/new')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: 'tmp/patient-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'tmp/patient-mobile.png' })
  const layout = await page.locator('dialog').evaluate(el => ({ width: el.scrollWidth, visible: el.clientWidth }))
  expect(layout.width).toBeLessThanOrEqual(layout.visible)
})
