import { test, expect } from '@playwright/test'

test('SQL console renders results and errors without losing SQL', async ({ page }) => {
  await page.goto('/tools/sql')
  const input = page.getByLabel('SQL', { exact: true })
  await input.fill("SELECT 42 AS number, NULL AS empty_value, '<script>test</script>' AS text_value")
  await page.getByRole('button', { name: '実行', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('1行表示')
  await expect(page.getByRole('region', { name: '実行結果' }).locator('tbody td')).toHaveText(['42', 'NULL', '<script>test</script>'])
  await input.fill('SELECT * FROM patients WHERE 0')
  await page.getByRole('button', { name: '実行', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('0行表示')
  await input.fill('DELETE FROM patients')
  await page.getByRole('button', { name: '実行', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('読み取り専用')
  await expect(input).toHaveValue('DELETE FROM patients')
  await page.screenshot({ path: 'tmp/sql-console.png' })
})

test('SQL pages and schema browser', async ({ page }) => {
  await page.goto('/tools/sql')
  await expect(page.getByRole('heading', { name: 'マスタ', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'patients', exact: true }).dblclick()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('cell', { name: 'id', exact: true })).toBeVisible()
  await expect(dialog.getByRole('columnheader', { name: '型', exact: true })).toBeVisible()
  await page.screenshot({ path: 'tmp/sql-schema.png' })
  await dialog.getByRole('button', { name: '閉じる' }).click()
  const input = page.getByLabel('SQL', { exact: true })
  await input.fill('WITH digits AS (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) SELECT a.n + b.n * 10 + c.n * 100 AS number FROM digits a, digits b, digits c ORDER BY number LIMIT 205')
  await page.getByRole('button', { name: '実行', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('200行表示')
  const result = page.getByLabel('SQL結果表', { exact: true })
  await result.evaluate(element => { element.scrollTop = 180 })
  const bounds = await result.evaluate(element => ({ top: element.getBoundingClientRect().top + element.clientTop, header: element.querySelector('thead').getBoundingClientRect().top }))
  expect(Math.abs(bounds.top - bounds.header)).toBeLessThan(1)
  await page.screenshot({ path: 'tmp/sql-scrolled.png' })
  await page.getByRole('button', { name: '次へ' }).click()
  await expect(page.getByRole('status')).toHaveText('5行表示')
  await expect(result.locator('tbody td')).toHaveText(['200', '201', '202', '203', '204'])
  await expect(page.getByRole('button', { name: '次へ' })).toBeDisabled()
  await page.getByRole('button', { name: '前へ' }).click()
  await expect(page.getByRole('status')).toHaveText('200行表示')
  await input.fill('SELECT 1')
  await expect(page.getByRole('button', { name: '次へ' })).toBeDisabled()
  await page.getByRole('button', { name: '実行', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('1行表示')
})
